[package]
name = "entities"
version = "0.1.0"
edition = "2024"

[dependencies]
sea-orm = { version = "1.1.16" }
serde = { version = "1.0.228", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }